### ISSUE TITLE
Can not Login.....

### ISSUE THREAD

**Issue by naturelan44** [devcartel/thomsonreuters#17]
hi, 
OS ： windows 64bit
Python： anaconda  python3.4
I try pyrfa for get real-time futures data of LME
I installed pyrfa, and run the timeseries.py(in "examples" directory), and it show "login failed" 
![image](https://cloud.githubusercontent.com/assets/9652807/18122533/78a48582-6f9c-11e6-88af-6926f47394d5.png)

I want to ask : I need config the pyrfa.cfg file use my own information(UserName, InstanceId, ApplicationId, Position)
![image](https://cloud.githubusercontent.com/assets/9652807/18122498/5bbb1fa8-6f9c-11e6-80bc-66cd0f29f63f.png)

**Comment by naturelan44** [comment]
or I can just use the default "pyrfa.cfg" directly?

**Comment by wiwat-tharateeraparb** [comment]
You need to get all those configs from your TREP-RT or Elektron admin.

**Comment by naturelan44** [comment]
ok, thank you~

**Comment by ehouarn-perret** [comment]
I'm facing the same issue, although I'm using another (corporate) .NET library that manages to connect using the same configuration and without making a fuss. I might some issues with converting my .NET library configuration to the PyRfa one.

I feel like I'm missing something, could you detail a bit more the expected format when you're willing to pass several servers in the connection server list node?

**Comment by ukrit-himakoon** [comment]
Hello Perret,

You can define a list of servers using "," as in the example below:

\Connections\Connection_RSSL\ServerList = "1.1.1.1,2.2.2.2,3.3.3.3"

or using hostname is also possible

\Connections\Connection_RSSL\ServerList = "hostname1,hostname2,hostname3"

Hope this helps,
